name: Build xd
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git lime https://github.com/kittycathy233/lime
          haxelib git hxcpp https://github.com/haxefoundation/hxcpp
          haxelib install openfl
          haxelib install flixel 4.11.0
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui 2.6.1
          haxelib install newgrounds 1.3.0
          haxelib install hscript 2.5.0
          haxelib install hscript-ex
          haxelib install polymod 1.5.2
          haxelib git linc_luajit https://github.com/andreirudenko/linc_luajit
          haxelib git faxe https://github.com/ashea-code/faxe
          haxelib git discord_rpc https://github.com/aidan63/linc_discord-rpc
      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true
          haxelib run lime rebuild hxcpp
      - name: Compile
        run: haxelib run lime build android
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: export/release/android/bin/app/build/outputs/apk/debug/*.apk
